version: '3'
services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      # [PATH_TO_POSTGRES_DATA]:/var/lib/postgressql/data/
      - /app/db-data:/var/lib/postgresql/data
  chainlink:
    image: "smartcontract/chainlink:1.11.0"
    # env_file: .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      # [PATH_TO_REPO_CHAINLINK_VOLUME]:/chainlink/
      - ./Chainlink:/chainlink/
     
    command: node start  --password ./Chainlink password.txt --api ./Chainlink apicredentials.txt 











# version: '3'
# services:
#   chainlink:
#     build: .
#     ports:
#       - "6688:6688"
#     volumes:
#       # [PATH_TO_REPO_CHAINLINK_VOLUME]:/chainlink/
#       - /Users/Documents/Chainlink/chainlink-volume/:/chainlink/
#     command: node start --password /Chainlink/password.txt --api /Chainlink/apicredentials.txt

#   db:
#     image: postgres:12
#     restart: always
#     environment:
#       POSTGRES_USER: db
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "5446:5432"
#     volumes:
#       - /app/db-data:/var/lib/postgresql/data


